---
- name: update apt cache
  sudo: yes
  apt: update_cache=yes cache_valid_time=3600

- name: upgrade apt
  sudo: yes
  apt: upgrade=yes

- name: install basic packages
  sudo: yes
  apt: name={{ item }} state=latest
  with_items:
    - build-essential
    - python-pip
    - python-dev
    - git
    - wget
    - vim
    - tmux

- name: install basic pip packages
  pip: name={{ item }}
  with_items:
    - tox
    - pytest
