# config file for automatic testing at travis-ci.org
language: python
sudo: false

python:
  - "2.7"
  - "3.4"

install:
  # install (the rest of the) dependencies
  - pip install -r requirements/development.txt

  # install your own package + executables
  - pip install .

script:
  # command to run tests and collect test coverage
  - coverage run --source chanjo setup.py test

after_success:
  coveralls
