language: python
sudo: false
python:
    - '3.6'

install:
    - mkdir -p ./bin
    - wget https://github.com/lomereiter/sambamba/releases/download/v0.5.8/sambamba_v0.5.8_linux.tar.bz2
    - tar xvjf sambamba_v0.5.8_linux.tar.bz2
    - mv sambamba_v0.5.8 ./bin/sambamba
    - chmod +x ./bin/sambamba
    - export PATH="${PATH}:${PWD}/bin"
    - pip install -q -r requirements-dev.txt .

script:
    - coverage run --source chanjo setup.py test

after_success: coveralls

notifications:
    email: never

deploy:
    provider: pypi
    user: robinandeer
    password:
        secure: fQsE+5FUuXWuLMuGVirfSEz7WBc09gxDbEcPfIJFUQ2FzaGCQ+OGZpb6sbNCrazhqwnyyJ7b4ZD3bjJ++kWsmnpgvdUFZRDUUpcLuDtwzPSxHVx/1Zax4gMnny83Z1yF4O7m8bXt7HG1mPuKzPSHLOcTg3SxTQEgSi27dkeY4WE=
    on:
        tags: true
        distributions: sdist bdist_wheel
        repo: Clinical-Genomics/chanjo
