# config file for automatic testing at travis-ci.org
language: python
sudo: false

python:
  - "2.7"
  - "3.5"

install:
  # install sambamba binary
  - mkdir -p ./bin
  - wget https://github.com/lomereiter/sambamba/releases/download/v0.5.8/sambamba_v0.5.8_linux.tar.bz2
  - tar xvjf sambamba_v0.5.8_linux.tar.bz2
  - mv sambamba_v0.5.8 ./bin/sambamba
  - chmod +x ./bin/sambamba
  - export PATH="${PATH}:${PWD}/bin"

  # install package and dependencies
  - pip install -q -r requirements-dev.txt .

script:
  # command to run tests and collect test coverage
  - coverage run --source chanjo setup.py test

after_success:
  coveralls
