# config file for automatic testing at travis-ci.org
language: python

python:
  - "2.7"
  - "3.4"

install:
  # install conda (if you have C-extension dependencies)
  - sudo pip install conda
  - sudo conda init
  - sudo conda config --set always_yes yes --set changeps1 no
  - sudo conda update conda

  # create a new conda env
  - conda create -q -p $HOME/py --file requirements/conda.txt "python=$TRAVIS_PYTHON_VERSION" sphinx pytest flake8 coverage
  - export PATH=$HOME/py/bin:$PATH

  # install (the rest of the) dependencies
  - pip install -r requirements/development.txt

  # install your own package + executables
  - pip install --editable .

  - conda info -a

script:
  # command to run tests and collect test coverage
  - coverage run --source chanjo setup.py test

after_success:
  coveralls
