# config file for automatic testing at travis-ci.org
language: python

python:
  - "2.7"
  - "3.4"

install:
  # install conda (if you have C-extension dependencies)
  - sudo pip install conda
  - sudo conda init
  - sudo conda update conda --yes

  # create a new conda env
  - conda create -p $HOME/py --yes $DEPS "python=$TRAVIS_PYTHON_VERSION"
  - export PATH=$HOME/py/bin:$PATH
  - conda install --yes --file requirements/conda.txt

  # install (the rest of the) dependencies
  - pip install -r requirements/development.txt --use-mirrors
  - pip install coveralls

  # install your own package + executables
  - pip install --editable .

  - conda info -a

script:
  # command to run tests and collect test coverage
  - coverage run --source chanjo setup.py test

after_success:
  coveralls
