---
- set_fact:
    sambamba_url: "https://github.com/lomereiter/sambamba/releases/download/v{{ sambamba_version }}/sambamba_v{{ sambamba_version }}_linux.tar.bz2"
    sambamba_exe: "{{ bin_dir }}/sambamba_v{{ sambamba_version }}"

- name: download and extract binary
  unarchive: src={{ sambamba_url }} dest="{{ bin_dir }}"
             creates="{{ sambamba_exe }}" copy=no mode="u+x"
  sudo: yes

- name: create unified alias
  file: src="{{ sambamba_exe }}" dest="{{ bin_dir }}/sambamba" state=link
  sudo: yes
