---
- name: update apt cache
  sudo: yes
  apt: update_cache=yes cache_valid_time=3600

- name: install basic packages
  sudo: yes
  apt: name={{ item }} state=latest
  with_items:
    - git
    - wget
    - vim
    - tmux

- name: copy dotfiles
  copy: src={{ item }} dest=~/.{{ item }}
  with_items:
    - tmux.conf
