#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Chanjo Sex Check - predict sex from BAM-alignment

Usage:
  chanjo-sex-check <bam_file> [--prepend=STR]
  chanjo-sex-check --help
  chanjo-sex-check --version

Arguments:
  <bam_file>          Path to BAM file

Options:
  -h --help           Show this screen
  -v --version        Show version
  -p --prepend=STR    Prepend to each contig Id [default: ]
"""
import sys

from chanjo.bam import BamFile
from chanjo.pyxshell import common
from chanjo import stages
from docopt import docopt


if __name__ == '__main__':
  # Parse docstring defined arguments
  args = docopt(__doc__, version='Chanjo Sex Check v1.0')

  # +------------------------------------------------------------------+
  # | Pre-process some input arguments & options
  # +------------------------------------------------------------------+
  prepend = args['--prepend']

  # SETUP: Connect to CoverageAdapter
  bam = BamFile(args['<bam_file>'])

  results = []
  # STEP 2: The Pipeline
  iter([(prepend + 'X', 1, 59373566), (prepend + 'Y', 69362, 11375310)]) \
    | stages.read_coverage(bam) \
    | stages.calculate_coverage() \
    > results

  sex = 'female'
  coverage_ratio = results[0] / results[1]
  if (results[0] > 0) and (coverage_ratio < 10):
    sex = 'male'

  sys.stdout.write('#chrX\tchrY\tsex\n')
  sys.stdout.write('\t'.join(map(str, results + [sex])) + '\n')
